In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:90% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:12pt;}
div.text_cell_render.rendered_html{font-size:12pt;}
div.output {font-size:12pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:12pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:12pt;padding:5px;}
table.dataframe{font-size:12px;}
</style>
"""))

<b><font size = "6" color = "red">ch11. 데이터프레임과 시리즈(Pandas) </font></b>

# 1절 판다스 패키지

- 데이터 분석을 위해 반드시 알아야 할 패키지. 넘파이를 기반으로 하며,
  다른 많은 라이브러리와 잘 통합 되도록 설계

- 2차원구조를 갖는 데이터프레임, 1차원 구조를 갖는 시리즈를 제공

- 판다스 장점: 데이터프레임 생성, 파일io, 레이블링, 부분데이터 추출, 크기 변경(행이나 열 삽입, 삭제), 데이터 분할, 병합, 데이터구조 변경, 결측치 처리
       
- https://pypi.python.org/pypi/pandas (package index)
- http://pandas.pydata.org/pandas-docs/stable/api.html (API reference)

In [3]:
import pandas as pd

'1.5.3'

In [8]:
data = pd.read_json('data/ch09_member1.json' ,encoding= 'cp949')
data

  Name  Age        Email Address
0  홍길동   30  hg@hong.com      서울
1  박길동   20  pg@hong.com      부산
2  신길동   25  sg@hong.com      대전

In [9]:
member4 = pd.read_csv('data/ch09_member4.csv') #기본 인코딩=utf-8
member4

   신길동  30  sg@hong.com  서울
0  홍길동  20  ho@hong.com  수원
1  마길동  25  ma@hong.com  안양

In [14]:
member1 = pd.read_csv('data/ch09_member1.csv',header=None, names=['name','age','email','address'])
member1

  name  age             email   address
0  홍길동   20  kildong@hong.com   서울시 관악구
1  김길동   40  kimdong@hong.com  서울시 영등포구
2  신길동   30  sindong@hong.com   서울시 동작구

# 2절 데이터프레임 만들기
## 2.1 딕셔너리 리스트를 이용해서 데이터 프레임 만들기

In [16]:
d = [{'kor':100, 'mat':80},{'kor':90, 'mat':80}]
df = pd.DataFrame(data=d)
df

   kor  mat
0  100   80
1   90   80

In [17]:
df.to_dict() # 데이터프레임을 딕셔너리로

{'kor': {0: 100, 1: 90}, 'mat': {0: 80, 1: 80}}

In [19]:
df.to_numpy() #데이터프레임을 넘파이 배열
df.values # 데이터프레임을 넘파이 배열

array([[100,  80],
       [ 90,  80]], dtype=int64)

In [27]:
df.dtypes # 열의 타입 확인
df.info() # ★★★정말 많이 쓰인다

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kor     2 non-null      int64
 1   mat     2 non-null      int64
 2   kot     2 non-null      float64
dtypes: float64(1), int64(2)
memory usage: 176.0 bytes

In [26]:
df['kor'].dtype

dtype('int64')

In [28]:
# 타입변경 (열마다)
import numpy as np
df['kot'] = df['kor'].astype(np.float64)

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kor     2 non-null      int64
 1   mat     2 non-null      int64
 2   kot     2 non-null      float64
dtypes: float64(1), int64(2)
memory usage: 176.0 bytes

In [30]:
d = [{'kor':100, 'mat':80},{'kor':90, 'mat':80},{'kor':92,'eng':99}]
df = pd.DataFrame(data=d)
df

   kor   mat   eng
0  100  80.0   NaN
1   90  80.0   NaN
2   92   NaN  99.0

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   kor     3 non-null      int64
 1   mat     2 non-null      float64
 2   eng     1 non-null      float64
dtypes: float64(2), int64(1)
memory usage: 200.0 bytes

In [34]:
df['kor'] = df['kor'].astype('int32')
df

   kor   mat   eng
0  100  80.0   NaN
1   90  80.0   NaN
2   92   NaN  99.0

In [35]:
# 결측치는 int로 형변환 불가(결측치를 대체값으로 치환 후 변환)

# 2.2 리스트를 이용해서 데이터 프레임 만들기

In [36]:
kor = [100,90,95,90,65]
mat = [99,100,95,98,94]
df = pd.DataFrame({'kor':kor,'mat':mat})
df.head(2) #상위 2행만

   kor  mat
0  100   99
1   90  100

In [37]:
np.c_[kor,mat]

array([[100,  99],
       [ 90, 100],
       [ 95,  95],
       [ 90,  98],
       [ 65,  94]])

In [39]:
df = pd.DataFrame(data=np.c_[kor,mat], columns=['국어','수학'])
df

    국어   수학
0  100   99
1   90  100
2   95   95
3   90   98
4   65   94

In [40]:
df.shape

(5, 2)

In [45]:
l = [['트렌드 코리아2026','김난도',18000,10],
    ['사탄탱고','라슬로',17820,10],
    ['미술관 여행자','카미유주노',29700,10]]
df= pd.DataFrame(l,columns=['책이름','저자','가격','할인율'])
df

           책이름     저자     가격  할인율
0  트렌드 코리아2026    김난도  18000   10
1         사탄탱고    라슬로  17820   10
2      미술관 여행자  카미유주노  29700   10

In [46]:
# %ls : ipython 매직명령어
# !dir: 쉘명령어

In [48]:
%ls "c:\aii\downloads\shareData\상가정보\"

 C 드라이브의 볼륨에는 이름이 없습니다.
 볼륨 일련 번호: A014-DCD6

 c:\aii\downloads\shareData\상가정보 디렉터리

2025-10-12  오후 03:33    <DIR>          .
2025-10-12  오후 03:33    <DIR>          ..
2025-04-27  오후 11:07             1,011 [필독]파일열람방법.txt
2025-04-27  오후 11:07        61,227,944 소상공인시장진흥공단_상가(상권)정보_강원_202503.csv
2025-04-27  오후 11:07       356,572,082 소상공인시장진흥공단_상가(상권)정보_경기_202503.csv
2025-04-27  오후 11:07        93,472,559 소상공인시장진흥공단_상가(상권)정보_경남_202503.csv
2025-04-27  오후 11:07        76,425,275 소상공인시장진흥공단_상가(상권)정보_경북_202503.csv
2025-04-27  오후 11:07        40,070,868 소상공인시장진흥공단_상가(상권)정보_광주_202503.csv
2025-04-27  오후 11:07        61,715,005 소상공인시장진흥공단_상가(상권)정보_대구_202503.csv
2025-04-27  오후 11:07        41,491,092 소상공인시장진흥공단_상가(상권)정보_대전_202503.csv
2025-04-27  오후 11:07        84,550,600 소상공인시장진흥공단_상가(상권)정보_부산_202503.csv
2025-04-27  오후 11:07       294,549,483 소상공인시장진흥공단_상가(상권)정보_서울_202503.csv
2025-04-27  오후 11:07         9,303,432 소상공인시장진흥공단_상가(상권)정보_세종_202503.csv
2025-04-27  오후 11:07        28,457,489 소상공인시장진흥공단_상가(상권)정보_울산_202503.csv
2025-04-27  오후 11:07        73,022,149 소상공인시장진흥공단_상가(상권)정보_인천_202503.csv
2025-04-27  오후 11:07        52,997,974 소상공인시장진흥공단_상가(상권)정보_전남_202503.csv
2025-04-27  오후 11:07        56,252,705 소상공인시장진흥공단_상가(상권)정보_전북_202503.csv
2025-04-27  오후 11:07        32,943,677 소상공인시장진흥공단_상가(상권)정보_제주_202503.csv
2025-04-27  오후 11:07        66,591,896 소상공인시장진흥공단_상가(상권)정보_충남_202503.csv
2025-04-27  오후 11:07        50,727,673 소상공인시장진흥공단_상가(상권)정보_충북_202503.csv
              18개 파일       1,480,372,914 바이트
               2개 디렉터리  162,159,759,360 바이트 남음

In [55]:
df = pd.read_csv(r'c:\aii\downloads\shareData\상가정보\소상공인시장진흥공단_상가(상권)정보_서울_202503.csv', nrows = 70)# encoding='utf-8', sep=',' 이거슨 기본값 생략해도 된다
df

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA010120220800000033,부동산임대김은숙,NaN,I2,음식,I212,비알코올,I21201,카페,I56229,...,1111014000100280021026727,NaN,서울특별시 종로구 삼청로 122-1,110230,3053,NaN,NaN,NaN,126.981840,37.586250
1,MA010120220800000036,한국황토건축연구소,NaN,L1,부동산,L102,부동산 서비스,L10203,부동산 중개/대리업,L68221,...,1165010800113080025020133,강남오피스텔,서울특별시 서초구 서초대로73길 40,137856,6612,NaN,11.0,NaN,127.024563,37.500924
2,MA010120220800000077,소망공인중개사사무소,NaN,L1,부동산,L102,부동산 서비스,L10203,부동산 중개/대리업,L68221,...,1120012200100040011000899,NaN,서울특별시 성동구 용답중앙15길 18,133847,4805,NaN,1.0,NaN,127.054262,37.564786
3,MA010120220800000084,고향집,NaN,I2,음식,I201,한식,I20101,백반/한정식,I56111,...,1111015400100800000000001,NaN,서울특별시 종로구 돈화문로4길 30,110430,3193,NaN,NaN,NaN,126.993820,37.570025
4,MA010120220800000090,보석나라,NaN,G2,소매,G217,시계·귀금속 소매,G21701,시계/귀금속 소매업,G47830,...,1153010700103590008007958,NaN,서울특별시 구로구 개봉로3길 23,152815,8353,NaN,1.0,NaN,126.855046,37.486242
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65,MA010120220800001555,미래디자인,NaN,M1,과학·기술,M114,인쇄·제품제작,M11401,명함/간판/광고물 제작,C33910,...,1111015500100210002017522,유덕빌딩,서울특별시 종로구 수표로18길 15,110420,3192,NaN,2.0,NaN,126.990424,37.569511
66,MA010120220800001558,화동커피,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1111014300101380021026977,NaN,서울특별시 종로구 율곡로3길 82,110230,3061,NaN,NaN,NaN,126.982271,37.579313
67,MA010120220800001579,포트폴리오,NaN,M1,과학·기술,M113,사진 촬영,M11301,사진촬영업,M73301,...,1111012400100800006017957,석탄회관,서울특별시 종로구 종로5길 58,110727,3151,NaN,1.0,NaN,126.980337,37.572906
68,MA010120220800001312,멋쟁이,NaN,G2,소매,G209,섬유·의복·신발 소매,G20902,여성 의류 소매업,G47412,...,1111013600100340031013750,NaN,서울특별시 종로구 인사동길 20-14,110290,3163,NaN,NaN,NaN,126.987299,37.572502
69,MA010120220800001337,라이브필,NaN,I2,음식,I211,주점,I21104,요리 주점,I56219,...,1144010500100260004003704,NaN,서울특별시 마포구 토정로37길 19,121875,4166,NaN,1.0,NaN,126.944940,37.541216

In [56]:
# 판다스 디스플레이 옵션
pd.options.display.max_columns = 39
pd.options.display.max_rows= 70

In [58]:
pd.options.display.max_columns

39

In [59]:
df.head(1)

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,표준산업분류명,시도코드,시도명,시군구코드,시군구명,행정동코드,행정동명,법정동코드,법정동명,지번코드,대지구분코드,대지구분명,지번본번지,지번부번지,지번주소,도로명코드,도로명,건물본번지,건물부번지,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA010120220800000033,부동산임대김은숙,NaN,I2,음식,I212,비알코올,I21201,카페,I56229,기타 비알코올 음료점업,11,서울특별시,11110,종로구,11110540,삼청동,1111014000,삼청동,1111014000100280021,1,대지,28,21.0,서울특별시 종로구 삼청동 28-21,111103100007,서울특별시 종로구 삼청로,122,1.0,1111014000100280021026727,NaN,서울특별시 종로구 삼청로 122-1,110230,3053,NaN,NaN,NaN,126.98184,37.58625

In [60]:
df.head(1).T

                                   0
상가업소번호          MA010120220800000033
상호명                         부동산임대김은숙
지점명                              NaN
상권업종대분류코드                         I2
상권업종대분류명                          음식
상권업종중분류코드                       I212
상권업종중분류명                       비알코올
상권업종소분류코드                     I21201
상권업종소분류명                          카페
표준산업분류코드                      I56229
표준산업분류명                 기타 비알코올 음료점업
시도코드                              11
시도명                            서울특별시
시군구코드                          11110
시군구명                             종로구
행정동코드                       11110540
행정동명                             삼청동
법정동코드                     1111014000
법정동명                             삼청동
지번코드             1111014000100280021
대지구분코드                             1
대지구분명                             대지
지번본번지                             28
지번부번지                           21.0
지번주소             서울특별시 종로구 삼청동 28-21
도로명코드                   111103100007
도로명                    서울특별시 종로구 삼청로
건물본번지                            122
건물부번지                            1.0
건물관리번호     1111014000100280021026727
건물명                              NaN
도로명주소            서울특별시 종로구 삼청로 122-1
구우편번호                         110230
신우편번호                           3053
동정보                              NaN
층정보                              NaN
호정보                              NaN
경도                         126.98184
위도                          37.58625

# 2.3 read_csv

In [62]:
# help(pd.read_csv)
# pd.read_csv() 함수 안에서 shift+tab+tab
pd.read_csv?

In [64]:
# (1) CSV파일 불러오기(기본 값)
member = pd.read_csv('data/ch11_member.csv', #, = encoding='utf-8',sep=',' , comment주석처리X 
                    )
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     6 non-null      object
 1   Age      6 non-null      int64
 2   Email    6 non-null      object
 3   Address  6 non-null      object
 4   Birth    6 non-null      object
dtypes: int64(1), object(4)
memory usage: 368.0+ bytes

In [73]:
# 문자형으로 읽어들인 Birth를 datetime형으로 
# 형변환 : astype('타입'), astype('datetime64' : 비추)
#         to_datetime()함수
# member['Birth'].astype('datetime64') #비추

member['Birth'] = pd.to_datetime(member['Birth'])
member.head(1)

  Name  Age          Email  Address      Birth
0  홍길동   20  hong@hong.com  서울시 강동구 1999-01-01

In [74]:
member['Age'] = member['Age'].astype(np.int16)
member.dtypes

Name               object
Age                 int16
Email              object
Address            object
Birth      datetime64[ns]
dtype: object

In [77]:
# (2) 특정행을 제외하고 csv파일 읽어오기
member = pd.read_csv('data/ch11_membercp949.csv',encoding='cp949', skiprows=[1,6] ) # 1,6번째 행 제외하고 읽어오기(시작은 1부터)
member

  Name  Age         Email  Address       Birth
0  홍길서   30  seo@hong.com   서울시 중구  1999-12-01
1  홍길남   21  nam@hong.com  서울시 강동구  1999-11-01
2  홍길북   22  buk@hong.com  서울시 관악구  1999-05-01
3  홍길중   23  mid@hong.com   부산시 중구  1999-01-30

In [81]:
# (3) 상위 몇 행만 sep문자는 , 가 아닌 csv파일 읽어오기
member = pd.read_csv('data/ch11_membersep.csv', nrows=5, #상위 5행만
                    sep='|')
member

  Name  Age          Email  Address       Birth
0  홍길동   20  hong@hong.com  서울시 강동구  1999-01-01
1  홍길서   30   seo@hong.com   서울시 중구  1999-12-01
2  홍길남   21   nam@hong.com  서울시 강동구  1999-11-01
3  홍길북   22   buk@hong.com  서울시 관악구  1999-05-01
4  홍길중   23   mid@hong.com   부산시 중구  1999-01-30

In [89]:
# (4) 주석(#) 제외, datetime형 필드를 지정하여 csv파일 읽어오기
member = pd.read_csv('data/ch11_membertab.csv',sep='\t', #구분자 설정,
                    comment='#',#주석제거,
                     parse_dates=['Birth']) # datetime64형으로 읽어 올 필드 지정
member.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     5 non-null      object
 1   Age      5 non-null      int64
 2   Email    5 non-null      object
 3   Address  5 non-null      object
 4   Birth    5 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 328.0+ bytes

# 2.4 패키지에서 가져오기: iris 데이터
- iris 가져오기 방법1: sklearn(머신러닝 패키지)
- iris 가져오기 방법2: statsmodels(R 데이터)
- iris 가져오기 방법3: seaborn(시각화패키지)
### 2.4.1 iris 방법1: sklearn
- sklearn.datasets 모듈데이터(iris)를 데이터 프레임으로 반환

In [94]:
from sklearn import datasets #머신러닝을 공부하기 위해 필요한 학습 데이터 셋 제공
# sklearn 패키지에서 제공되는 데이터셋은 딕셔너리형식으로 제공
iris = datasets.load_iris()
iris # Bunch타입(딕셔너리를 상속받은 타입) 딕셔너리처럼 동작
# print(iris.DESCR) # iris데이터 셋의 설명
print(iris.keys())

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [96]:
iris.data #독립변수
iris['data'][:3] #상위 3행

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2]])

In [97]:
# 데이터프레임의 열이름(비추)
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [102]:
# 데이터프레임의 열이름(강추)
[col[:-5].replace(' ', '_') for col in iris.feature_names]

['sepal_length', 'sepal_width', 'petal_length', 'petal_width']

In [103]:
iris.target #타겟변수(종속변수) ML/DL 학습시 타겟변수(종속변수)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [104]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [105]:
iris.target_names[iris.target] #데이터프레임에 쓸 타겟변수(가장 오른쪽 열)

'setosa'

In [107]:
#독립변수
data = iris.data
# 종속변수
target= iris.target_names[iris.target].reshape(-1,1)
print(data[:3], target[:3])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]] [['setosa']
 ['setosa']
 ['setosa']]

In [108]:
print('독립변수 shape: ',data.shape)
print('타겟변수 shape: ',target.shape)

독립변수 shape:  (150, 4)
타겟변수 shape:  (150, 1)

In [113]:
# 1. 독립변수랑 종속변수를 stack한 후 데이터 프레임으로 
df= pd.DataFrame(np.hstack((data,target)),
                columns=iris.feature_names + ['species'])
df

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica
146,6.3,2.5,5.0,1.9,virginica
147,6.5,3.0,5.2,2.0,virginica
148,6.2,3.4,5.4,2.3,virginica
149,5.9,3.0,5.1,1.8,virginica

In [114]:
df.specie
df['species']

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [117]:
# df['speal length(cm)']
df.columns=[col[:-5].replace(' ','_') for col in iris.feature_names]+['species']
df.head(1)

  sepal_length sepal_width petal_length petal_width species
0          5.1         3.5          1.4         0.2  setosa

In [118]:
#2. 독립변수, 종속변수를 따로 데이터 프레임으로 생성-> 두 데이터프레임 연결
X = pd.DataFrame(iris.data,columns=[col[:-5].replace(' ','_') for col in iris.feature_names])
X.head(1)

   sepal_length  sepal_width  petal_length  petal_width
0           5.1          3.5           1.4          0.2

In [123]:
Y = pd.DataFrame(iris.target_names[iris.target],columns=['species'])
Y.head(1)

  species
0  setosa

In [124]:
print('X의 shape:', X.shape)
print('Y의 shape:', Y.shape)
print('X의 index:', X.index)
print('Y의 index:', Y.index)

X의 shape: (150, 4)
Y의 shape: (150, 1)
X의 index: RangeIndex(start=0, stop=150, step=1)
Y의 index: RangeIndex(start=0, stop=150, step=1)

In [125]:
iris_df = pd.concat([X,Y], axis=1) # 두개의 데이터프레임을 열로 연결
iris_df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]